---
title: 'SOIL LAB DATA ANALYSIS'
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
```
loading data
```{r}
ICPMS <- read.csv("~/CHEM313_L4_SoilLab/data/tidy_ICPMS.csv")
ICPMS
```
defining lists
```{r}
sample_sites <- unique(filter(ICPMS, site!="MB", site!="")$site) #exclude method blank and quality control from list of sites
sample_sites
metals_analyzed <- unique(ICPMS$metal)
metals_analyzed
```
using loops to create a calibration curve for each metal
```{r}
#forloop with filtered out calibration data
ICPMS_cal <- NULL
for (unique_metal in metals_analyzed) {
  cal <- ICPMS %>%
    filter(type == "Cal1" | type == "Cal2" | type == "Cal3") %>%
    filter(metal == unique_metal) %>%
    select(concentration, cps, rsd) 
  #performing linear regression
  w <- 1/(cal$cps*cal$rsd)^2
  model <- lm(cal$cps ~ cal$concentration, weights = w)
  
  slope <- model$coefficients[2]
  intercept <- model$coefficients[1]
  slope_std <- summary(model)$coefficients[2,2]
  intercept_std <- summary(model)$coefficients[1,2]
  
  plot(cal$cps ~ cal$conc,
       xlab = paste("Concentration of", unique_metal, "(ppb)"),
       ylab = "Counts per second") +
    abline(model, col="blue") +
    title(paste("Calibration for", unique_metal))
  
  equation <- data_frame(metal = unique_metal, slope, slope_std, intercept, intercept_std)
  ICPMS_cal <- rbind(ICPMS_cal, equation)
}

ICPMS_cal
#clean up
rm(equation, cal, slope, slope_std, intercept, intercept_std, w, model, unique_metal)
```
function to analyze samples with comments for inputs and outputs
```{r}
#inputs: unique_site (character, e.g. A)
#outputs: concentration vector

sample_analysis <- function(unique_site) {
  concentration_data <- NULL
  #forloops select specific sample and specific metal
  for (unique_metal in metals_analyzed) {
    sample <- filter(ICPMS, metal == unique_metal, site == unique_site)
    data <- NULL
    for (ID in sample$sample_key) {
      sample_data <- filter(sample, sample_key == ID)
      cal <- filter(ICPMS_cal, metal == unique_metal)
      #sample analysis
      m <- cal$slope
      b <- cal$intercept
      y <- sample_data$cps
      b_e <- cal$intercept_std
      m_e <- cal$slope_std
      x <- (y-b)/m
      RSD <- sample_data$rsd
      CPS <- sample_data$cps
      #error propagation
      e_yb <- sqrt((RSD)^2 + (b_e)^2) #error in y-b in calibration
      yb <- CPS-b
      e_x <- x*sqrt((e_yb/yb)^2+(m_e/m)^2) #error in x from calibration
      #storing concentration data for sites that are NOT method blanks
      data <- rbind(data, data_frame(sample_key = ID, x, e_x))
      if (unique_site != "MB"){
        concentration_data <- data_frame(sample_key = sample_data$sample_key,
                                         analyst = sample_data$analyst,
                                         metal = unique_metal,
                                         site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x)%>%
          rbind(concentration_data)
      }
    }
    #storing site method blanks by averaging concentrations
      if (unique_site == "MB") {
        x <- mean(data$x)
        e_x <- sd(data$x)
        concentration_data <- data_frame(metal = unique_metal,
                                         site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
          rbind(concentration_data)
      }
  }
  return(concentration_data)
}
```
function to run different function on each soil sample site
```{r}
#inputs: a function
#outputs: a dataframe with function outputs from each site

run_sites <- function(Function) {
  value <- NULL
  for (sites in sample_sites) {
    site_value <- Function(sites)
    value <- rbind(site_value, value)
  }
  return(value)
}
```
analyzing method blank and samples
```{r}
MB <- sample_analysis("MB") #(ug/kg)
uncor_sample <- run_sites(sample_analysis) #values do no account for dilutions (ug/kg)

MB
uncor_sample
```
correcting for method blank
```{r}
sample_data_mb <- NULL

for (unique_metal in metals_analyzed) {
  MB_metal <- filter(MB, metal == unique_metal)
  sample_metal <- filter(uncor_sample, metal == unique_metal)
  conc_dil_blanked <- sample_metal$conc_dil - MB_metal$conc_dil
  #error propagation: subtraction of MB
  conc_dil_blanked_error <- sqrt((sample_metal$conc_dil_error)^2 + (MB_metal$conc_dil_error)^2)
  sample_data_mb <- sample_metal %>%
    mutate(conc_dil_blanked, conc_dil_blanked_error) %>%
    rbind(sample_data_mb)
}

sample_data_mb
```

