---
title: 'L4 AA Analysis'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

##AA analysis
goals of analysis
look at metals at different sites (compare means?)
instrumentation - compare how ICPMS and AA differ for Cr

loading data
```{r}
AA <- read.csv("~/CHEM313_L4_SoilLab/data/tidy_AA.csv")
```
defining lists
```{r}
sample_sites <- unique(filter(AA, site!="MB", site!="")$site)
```
making cal curve
```{r}
cal <- AA %>%
  filter(type == "CalStd" | type == "CalStd2" | type == "CalStd4") %>%
  select(concentration, mean_abs, percent_rsd)
  
model <- lm(cal$mean_abs ~ cal$concentration)
slope <- model$coefficients[2]
intercept <- model$coefficients[1]
slope_std <- summary(model)$coefficients[2,2]
intercept_std <- summary(model)$coefficients[1,2]
  
plot(cal$mean_abs ~ cal$concentration,
     xlab = "Concentration of Cr (ppb)",
     ylab = "Absorbance") +
  abline(model, col="blue") +
  title("Calibration for Cr")

AA_cal <- tibble(slope, slope_std, intercept, intercept_std)
AA_cal
#clean up
rm(cal, slope, slope_std, intercept, intercept_std, model)
```

fitting samples to cal curve
```{r}
AA_sample <- filter(AA, site != "")
m <- AA_cal$slope
b <- AA_cal$intercept
y <- AA_sample$mean_abs
b_e <- AA_cal$intercept_std
m_e <- AA_cal$slope_std
x <- (y-b)/m
RSD <- AA_sample$percent_rsd/100
ABS <- AA_sample$mean_abs
#error propagation
e_yb <- sqrt((RSD)^2 + (b_e)^2) #error in y-b in calibration
yb <- ABS-b
e_x <- x*sqrt((e_yb/yb)^2+(m_e/m)^2) #error in x from calibration
#storing concentration data for sites that are NOT method blanks

AA_concentration_data <- tibble(sample_key = AA_sample$sample_key,
                                         analyst = AA_sample$analyst,
                                         site = AA_sample$site,
                                         conc_dil = x,
                                         conc_dil_error = e_x)

AA_concentration_data
```

