---
title: "SOIL LAB"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(janitor)
```

## ICPMS data

Importing data
```{r, warning=FALSE, message=FALSE}

ICPMS_imported <- read.csv("~/CHEM313_L4_SoilLab/data/ICPMS_Data.csv",
                         skip=1,
                         na="N/A")
sample_key <- read.csv("~/CHEM313_L4_SoilLab/data/Sample_Key.csv", skip=0)
```


Tidying Data
```{r}

RSD_data <- ICPMS_imported %>% 
  select(Cr52 = CPS.RSD,
         Cr53 = CPS.RSD.1,
         As75 = CPS.RSD.2,
         Cd111 = CPS.RSD.3,
         Cd114 = CPS.RSD.4,
         Pb208 = CPS.RSD.5,
         Ge_RSD = CPS.RSD.7,
         Sample.Key) %>% 
  pivot_longer(cols = 1:6, names_to = "Metal", values_to = "RSD")

ICPMS_tidy <- ICPMS_imported %>% 
  select(Cr52 = CPS,
         Cr53 = CPS.1,
         As75 = CPS.2,
         Cd111 = CPS.3,
         Cd114 = CPS.4,
         Pb208 = CPS.5,
         Ge72 = CPS.7,
         Sample.Key) %>%
  pivot_longer(1:6, names_to = "Metal", values_to = "CPS") %>%
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
         CPS=CPS/Ge72) %>%
  select(-Ge72)

all(RSD_data$Sample.Key==ICPMS_tidy$Sample.Key, RSD_data$Metal==ICPMS_tidy$Metal)
```

Merging Tidy data with Sample Key
```{r}
ICPMS_merged <- merge(ICPMS_tidy, sample_key)
```

## FAAS (flame atomic absorption spectroscopy) data

Importing data
```{r, warning=FALSE, message=FALSE}

AA_imported <- read_csv("~/CHEM313_L4_SoilLab/data/AA_Data.csv", col_types = cols(`%RSD` = col_number()), skip = 4, na = "N/A") %>% rename(Sample.Key = "Sample Key")

sample_key <- read.csv("~/CHEM313_L4_SoilLab/data/Sample_Key.csv", skip=0)
```

Merging data
```{r}
AA_merged <- merge(AA_imported, sample_key)
```

Decluttering Environment
```{r, warning = FALSE}
rm(list= ls()[!(ls() %in% c("ICPMS_merged","AA_merged"))])
clean_names(AA_merged, "snake")
clean_names(ICPMS_merged, "snake")
```

Save as csv file
```{r}
write.csv(ICPMS_merged, file = "~/CHEM313_L4_SoilLab/data/tidy_ICPMS.csv")
write.csv(AA_merged, file = "~/CHEM313_L4_SoilLab/data/tidy_AA.csv")
```

